name: Build and deploy JAR app to Azure Web App - tkg-tk-dev-apps-gscm

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Windows, x64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - name: Build with Maven
        run:
          cd C:\actions-runner\_work\tkg-devops\tkg-devops\demo
          mvn clean install    

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
          # path: '$/demo/build/libs/*SNAPSHOT.jar'
          

          
  deploy:
    runs-on: [self-hosted, Windows, x64]
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tkg-tk-dev-apps-gscm'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_394733613D8947BCB0D57A0B2CCCEF7D }}
          package: '*.jar'
